apiVersion: v1
kind: Secret
metadata:
  name: postgres-login
  namespace: wo-ns
type: Opaque
data:
  special.postuser: cG9zdGdyZXMK
  special.postpassword: TXlWOWV2VnlnZA==
  special.uripostgres: bG9pY2stcG9zdGdyZXMtcG9zdGdyZXNxbC5wb3N0Z3Jlcy5zdmMuY2x1c3Rlci5sb2NhbAo=
  special.postport: NTQzMgo=
  special.dbase: d28tZGF0YWJhc2UK